services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks:
      - broker
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    networks:
      - broker
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  db:
    image: mysql
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - broker
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234567
      MYSQL_DATABASE: userdb

  api:
    build:
      context: ./apiuser
      dockerfile: Dockerfile
    image: apiuser/users:1.0
    links:
      - db
    networks:
      - broker
    depends_on:
      - db
    ports:
      - 8080:8080

volumes:
  dbdata:

networks:
  broker:
    driver: bridge