spring:
  kafka:
    consumer:
      bootstrap-servers: kafka:29092
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  datasource:
    url: jdbc:mysql://db:3306/userdb?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: 1234567
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      ddl-auto: update
      jdbc: time_zone = TimeZone
    show-sql: true

  jackson:
    default-property-inclusion: NON_NULL

topic:
  message-action-user: topic_message_action_user